---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chains-config
  labels:
    app.kubernetes.io/component: chains
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
    pipeline.tekton.dev/release: "devel"
    version: "v0.5.0"
